force-app/main/default/objects/Incident__c/Incident__c.object-meta.xml
<CustomObject>
    <label>Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incident__c/fields/IncidentNumber__c.field-meta.xml
<CustomField>
    <fullName>IncidentNumber__c</fullName>
    <label>IncidentNumber</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incident__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IncidentHandler.cls
public class IncidentHandler {
    
    @auraEnabled(cacheable=true)
    public static List<Incident__c> searchIncidents(String incidentNumber,String Status){
        
        List<Incident__c> incidentList = [SELECT Id,Status__c,IncidentNumber__c FROM Incident__c 
                                                 WHERE Status__c =:Status AND IncidentNumber__c=:incidentNumber];
        System.debug('incidentList__'+incidentList[0]);
         return incidentList;
    }

}